apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: menu-service
  template:
    metadata:
      labels:
        app: menu-service
    spec:
      containers:
        - name: menu-service
          image: pixelopscloud/restaurant-app-menu-service:b2809e9ea7d1c26b60ea394d6cd53c3c71f82d97
          imagePullPolicy: Never
          ports:
            - containerPort: 3002
          env:
            - name: MONGO_URI
              value: mongodb://mongodb:27017/restaurant

---
apiVersion: v1
kind: Service
metadata:
  name: menu-service
spec:
  selector:
    app: menu-service
  ports:
    - port: 3002
      targetPort: 3002
