apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: pixelopscloud/restaurant-app-order-service:b2809e9ea7d1c26b60ea394d6cd53c3c71f82d97
          imagePullPolicy: Always
          ports:
            - containerPort: 3003
          env:
            - name: MONGO_URI
              value: mongodb://mongodb:27017/restaurant

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - port: 3003
      targetPort: 3003
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
